#!/bin/bash

	python2.7 nodemcu-uploader/nodemcu-uploader.py upload  \
			src/init_$1.lua:init.lua \
			src/buttons.lua:buttons.lua \
			src/tcp_server.lua:tcp_server.lua \
			src/main.lua:main.lua --restart


