#!/bin/bash

if [ $# == 0 ];
then
	python2.7 nodemcu-uploader/nodemcu-uploader.py upload  \
			src/init.lua:init.lua \
			src/main.lua:main.lua --restart


else
		python2 nodemcu-uploader/nodemcu-uploader.py  upload src/$1.lua:$2.lua --restart
fi
